### ISSUE TITLE
Coding standards for the project

### ISSUE THREAD

**Issue by dklimkin** [ibrdtn/ibrdtn#228]
Sorry this is more of a question rather than a bug. I couldn't find contributor's guidelines on wiki. I'd like to find out:

1. What is the target C++ version? Will C++11/14/17 code be accepted?
2. RAII doesn't seem to be used, is it ok for new code / refactorings?
3. What's the plan on exceptions? Those seem to be used in some places but not others. Is it recommended for new code? Is it ok to avoid them (normally I'd avoid them for C++)?
4. I am slightly confused on the structure, e.g. ibrcommon vs ibrdtn libs, and artifacts like:
  ./ibrdtn/ibrdtn/ibrdtn/ibrdtn.h
Are there any existing plans on restructuring?

Thanks.

**Comment by morgenroth** [comment]
Guidelines are now added to https://github.com/ibrdtn/ibrdtn/wiki/Developer-Guidelines.

They do not include any statement to RAII. While this pattern is recommended and even used in IBR-DTN were reasonable, I think you mean something different than explained in https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization. Can you elaborate on that?

To point 4: Yes. It was on a roadmap to split the repository in its parts (ibrcommon, ibrdtn, daemon, tools, android). Due to many reasons and time constrains this did not happened yet.

**Comment by dklimkin** [comment]
Thanks, that's useful to have!

for (2), I generally meant std::unique_ptr / std::shared_ptr / std::lock_guard etc. The C++ standard section clarifies this now.

for (4), I'd like to take a bite on this if you don't mind. This can take some time though, and likely should be on a branch.

**Comment by morgenroth** [comment]
for (4): the plan was to split the repository while keeping the individual history logs. This is a bit more complicated, but keeps past changes trackable.

**Comment by dklimkin** [comment]
Do you mean into separate git repos and github projects? What would be the benefits versus just top-level directories?

**Comment by morgenroth** [comment]
I mean separate git repos. Separate repositories allow to run CI individually and also have a versions (commit hashes) for each logical unit. If you look at the releases in the past. There are .tar.gz and debian packages for ibrcommon, ibrdtn, ibrdtnd, and ibrdtn-tools. I see no benefit in just reorganizing the folder structure.

Maybe it makes sense to split the repository in three:
 - ibrcommon (because it is generic and not hard related to DTN)
 - ibrdtn (with a new structure and configure.ac in the root)
 - android-ibrdtn (Just the Android part)

The tricky part is especially the Android part. In order to compile the NDK stuff, symbolic links are created to point to the ibrcommon, ibrdtn, and daemon folder. This must be handled somehow. Maybe with git submodules or a script which organizes the inclusion.

**Comment by dklimkin** [comment]
Where would the daemon and tools land in this layout? For ibrcommon, are there ibrcommon users that is not ibrdtn?

Individual Cl runs are faster, but it may result in ibrcommon change that breaks, e.g. daemon, to get merged. It would also make migrations harder, e.g. for an interface change two patches must land on two repository simultaneously and result in some onworkable combinations.

**Comment by morgenroth** [comment]
Yes, there are other projects which use ibrcommon. I know at least some non-public ones.
I think it is ok have daemon and tools together with the ibrdtn lib, because they are tightly coupled belong to the same topic.

The point with the interface change is correct, but in that case you have to work iteratively and bind a release to a specific version. E.g. the new interface would be part of ibrcommon 2.x while ibrdtn have to stick to the old interface as long as there is no refactored version.

**Comment by dklimkin** [comment]
Would you mind if irbdtn, daemon and tools would be top-level, as the first step? If repo gets split after, that would be continuation of this change (e.g. directories turned into submodules). It's weird now the library is nested under 3 levels of ibrdtn/ibrdtn/ibrdtn dirs.

**Comment by morgenroth** [comment]
Larger structure changes may scramble the commit history in a way that it is no longer possible to investigate the reason for specific changes. I am not sure if would be really the case, but it is an assumption of mine. Moreover, I do not think that anything that someone could do in that direction would convince me, because the idea of splitting the repositories is years old and still the only option in my opinion.

I recommend that you do not waste your time/patience and better work on the feature you like to add rather than fixing my personal neurosis.
