### ISSUE TITLE
Unable to include bundlecore.h

### ISSUE THREAD

**Issue by gm-28** [ibrdtn/ibrdtn#285]
Hi,

I need to be able to access the bundlecore object in dtnrecv so that i can remove the bundles from the register as i receive them.
Right now i'm including it like this #include "../../daemon/src/core/BundleCore.h" , however this way the component.h is not found.
Can i change this in the makefile of the tools directory?

Thanks in advance!

The error message:
make  all-am
make[1]: Entering directory '/home/moreira/Documents/ibrdtn/ibrdtn/tools/src'
  CXX      dtnrecv.o
In file included from dtnrecv.cpp:24:0:
../../daemon/src/core/BundleCore.h:25:10: fatal error: Component.h: No such file or directory
 #include "Component.h"
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:712: recipe for target 'dtnrecv.o' failed
make[1]: *** [dtnrecv.o] Error 1
make[1]: Leaving directory '/home/moreira/Documents/ibrdtn/ibrdtn/tools/src'
Makefile:452: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by morgenroth** [comment]
BundleCore is part of the dtnd binary and not included in the base library. You cannot access it from a client as dtnrecv. It's a long time ago since I have been working on ibrdtn but I think there is no need to remove bundles manually. If bundles are delivered as singleton, they will be purged automatically.

Maybe you need to rethink your proposal.
